

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/datajpa?allowPublicKeyRetrieval=true
    username: root
    password: '!zxa753951'


  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: false
    #    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate:
        default_batch_fetch_size: 100
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
   # database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 2000

logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace
server:
  address: localhost
  port: 8080