spring:
  application:
    name: chat
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpass
      database: chat_app
      port: 27017
      host: localhost
server:
  port: 8088